# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-08 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import ecommerce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='SOME STRING', max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('descrition', models.CharField(default='SOME STRING', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='SOME STRING', max_length=250)),
                ('alt', models.CharField(default='SOME STRING', max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to=ecommerce.models.upload_images)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='SOME STRING', max_length=250)),
                ('descrition', models.CharField(default='SOME STRING', max_length=250)),
                ('price', models.IntegerField()),
                ('slug', models.SlugField(max_length=250)),
                ('category', models.ManyToManyField(to='ecommerce.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='SOME STRING', max_length=250)),
                ('descrition', models.CharField(default='SOME STRING', max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to=ecommerce.models.upload_images)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='images',
            field=models.ManyToManyField(to='ecommerce.Image'),
        ),
    ]
