# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ecommerce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('descrition', models.CharField(blank=True, default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=250)),
                ('message', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('alt', models.CharField(blank=True, default='', max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('image_img', models.ImageField(blank=True, null=True, upload_to=ecommerce.models.upload_images)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('phone', models.IntegerField()),
                ('message', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('descrition', models.CharField(blank=True, default='', max_length=250)),
                ('price', models.IntegerField()),
                ('slug', models.SlugField(max_length=250)),
                ('images', models.ImageField(blank=True, null=True, upload_to=ecommerce.models.upload_images)),
                ('category', models.ManyToManyField(to='ecommerce.Category')),
                ('product_images', models.ManyToManyField(to='ecommerce.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('descrition', models.CharField(blank=True, default='', max_length=250)),
                ('slider_img', models.ImageField(blank=True, null=True, upload_to=ecommerce.models.upload_images)),
            ],
        ),
        migrations.CreateModel(
            name='SocailMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('descrition', models.CharField(blank=True, default='', max_length=250)),
                ('images', models.ImageField(blank=True, null=True, upload_to=ecommerce.models.upload_images)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Product'),
        ),
        migrations.AddField(
            model_name='category',
            name='cat_img',
            field=models.ManyToManyField(to='ecommerce.Image'),
        ),
    ]
